[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HierarchicalGaussianFiltering = "63d42c3e-681c-42be-892f-a47f35336a79"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[sources]
HierarchicalGaussianFiltering = {rev = "c0404294082fdc358d680a04a63eb9bfa9182ccc", url = "https://github.com/ComputationalPsychiatry/HierarchicalGaussianFiltering.jl"}

[compat]
Distributions = "=0.25.126"
HierarchicalGaussianFiltering = "=0.7.0"
JSON3 = "=1.14.3"
julia = "1.11"
